-- APEX Universal AI OS — initial schema
-- Tables backing the env-gated persistence layer in src/db.py.

-- Single-row snapshot of the autonomous revenue engine.
create table if not exists revenue_state (
    id              integer primary key default 1,
    total_revenue   numeric      not null default 0,
    monthly_revenue jsonb        not null default '{}'::jsonb,
    updated_at      timestamptz  not null default now(),
    constraint revenue_state_singleton check (id = 1)
);

-- Customer entitlements, driven by Stripe webhook events.
create table if not exists subscriptions (
    customer_id text        primary key,
    plan_id     text,
    status      text        not null default 'active',
    updated_at  timestamptz not null default now()
);

-- Breakthrough candidates generated by the BreakthroughEngine (optional log).
create table if not exists breakthroughs (
    id          text        primary key,
    title       text        not null,
    domain      text        not null,
    method      text        not null,
    novelty     real        not null,
    impact      real        not null,
    feasibility real        not null,
    score       real        not null,
    rationale   text,
    created_at  timestamptz not null default now()
);

create index if not exists breakthroughs_score_idx on breakthroughs (score desc);
